"""
Django settings for DjangoPlus project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '8qp@7ko#54)m(&b$8-qs7)myo*ma$fh2sd15q(r&jb7a347dd1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'xadmin',
    'crispy_forms',
    'rest_framework',
    'demo'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'DjangoPlus.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'DjangoPlus.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

# Celery settings
from kombu import Queue, Exchange

CELERY_CONFIG_DETAIL_DICT = dict(
    CELERY_BROKER_URL='pyamqp://guest@localhost//',  # 代理人的网址
    CELERY_ACCEPT_CONTENT=['pickle', 'json', 'msgpack', 'yaml'],  # 指定任务接受的内容序列化类型(序列化)
    # CELERY_RESULT_BACKEND='db+sqlite:///results.sqlite',  # 结果存储地址
    # CELERY_RESULT_SERIALIZER='json',  # 结果存储序列化格式为 json
    CELERYD_TASK_TIME_LIMIT=60,  # 任务超出5秒将被kill
    CELERYD_PREFETCH_MULTIPLIER=4,  # 每次预取４个
    CELERYD_FORCE_EXECV=True,  # 防止死锁
    CELERYD_MAX_TASKS_PER_CHILD=500,  # 每个worker最多执行500次个任务就会被释放掉, 可防止内存泄露
    CELERY_DISABLE_RATE_LIMITS=True,  # 关闭限速
    CELERY_TASK_SERIALIZER='json',  # 任务序列化方式

    CELERY_QUEUES=(
        Queue('default', Exchange('default'), routing_key='default', exchange_type="topic"),
        Queue('big_task', Exchange('big_task'), routing_key='big_task', exchange_type="topic"),
        # 路由键以 task. 开头的消息进入此队列
        Queue('small_task', Exchange('small_task'), routing_key='small_task', exchange_type="topic")
    ),
    CELERY_DEFAULT_QUEUE='default',  # 默认队列
    CELERY_DEFAULT_EXCHANGE='default',  # 默认交换所
    CELERY_DEFAULT_EXCHANGE_TYPE='topic',  # 默认交换所
    CELERY_DEFAULT_ROUTING_KEY='default'  # 默认交换机路由键
)
