# Generated by Django 2.2.1 on 2019-05-17 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
